export const CAMPAIGN_TITLE_MAX_LENGTH = 100;
export const CAMPAIGN_DESCRIPTION_MAX_LENGTH = 2000;
export const CAMPAIGN_DESCRIPTION_MIN_LENGTH = 50;
export const ROUND_TITLE_MAX_LENGTH = 100;
export const ROUND_DESCRIPTION_MAX_LENGTH = 2000;
export const FUNDING_USAGE_MAX_LENGTH = 1000;
export const FUNDING_USAGE_MIN_LENGTH = 50;
